runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html
  expiration: "0m"

- url: /style/(.*\.css)
  mime_type: text/css
  static_files: style/\1
  upload: style/(.*\.css)

- url: /favicon/(.+)
  static_files: favicon/\1  
  upload: favicon/(.*)

- url: /img/(.+)
  static_files: img/\1  
  upload: img/(.*)

- url: /video/(.+)
  mime_type: video/mp4
  static_files: video/\1
  upload: video/(.*)

- url: /manifest.json
  mime_type: application/json
  static_files: manifest.json
  upload: manifest.json

- url: /(.*)/$
  mime_type: text/html
  static_files: src/\1/index.html
  upload: src/.*/index.html
  expiration: "0m"

- url: /(.*)$
  mime_type: text/html
  static_files: src/\1/index.html
  upload: src/.*/index.html
  expiration: "0m"

